INSERT INTO movie (title, genre, rating) VALUES
    ('Avengers: Endgame', 'ACTION', 8.4),
    ('The Pursuit of Happyness', 'DRAMA', 8.0),
    ('Inception', 'SCI_FI', 8.8),
    ('Titanic', 'ROMANCE', 7.8),
    ('The Conjuring', 'HORROR', 7.5),
    ('The Dark Knight', 'ACTION', 9.0),
    ('Forrest Gump', 'DRAMA', 8.8),
    ('Interstellar', 'SCI_FI', 8.6),
    ('The Shawshank Redemption', 'DRAMA', 9.3),
    ('Jurassic Park', 'ACTION', 8.1),
    ('The Matrix', 'SCI_FI', 8.7),
    ('Fight Club', 'DRAMA', 8.8),
    ('Inglourious Basterds', 'ACTION', 8.3),
    ('Pulp Fiction', 'DRAMA', 8.9),
    ('The Godfather', 'DRAMA', 9.2),
    ('Star Wars: A New Hope', 'SCI_FI', 8.6),
    ('The Terminator', 'ACTION', 8.0),
    ('Schindler''s List', 'DRAMA', 9.0),
    ('The Silence of the Lambs', 'THRILLER', 8.6),
    ('Gladiator', 'ACTION', 8.5),
    ('Casablanca', 'ROMANCE', 8.5),
    ('Goodfellas', 'DRAMA', 8.7),
    ('The Departed', 'THRILLER', 8.5),
    ('Back to the Future', 'SCI_FI', 8.5),
    ('The Big Lebowski', 'COMEDY', 8.1),
    ('The Avengers', 'ACTION', 8.1),
    ('The Grand Budapest Hotel', 'COMEDY', 8.1),
    ('The Revenant', 'DRAMA', 8.0),
    ('Blade Runner', 'SCI_FI', 8.1),
    ('Zombieland', 'COMEDY', 7.6),
    ('Deadpool', 'COMEDY', 8.0),
    ('Jumanji: Welcome to the Jungle', 'COMEDY', 7.0),
    ('The Hangover', 'COMEDY', 7.7),
    ('Star Wars: The Empire Strikes Back', 'SCI_FI', 8.7),
    ('Guardians of the Galaxy', 'ACTION', 8.0),
    ('The Truman Show', 'DRAMA', 8.1),
    ('Django Unchained', 'DRAMA', 8.4),
    ('Mad Max: Fury Road', 'ACTION', 8.1),
    ('The Usual Suspects', 'THRILLER', 8.5),
    ('A Clockwork Orange', 'DRAMA', 8.3),
    ('The Prestige', 'DRAMA', 8.5),
    ('Shutter Island', 'THRILLER', 8.2),
    ('Parasite', 'DRAMA', 8.6),
    ('Jaws', 'THRILLER', 8.0),
    ('Se7en', 'THRILLER', 8.6),
    ('The Shining', 'HORROR', 8.4),
    ('American Psycho', 'THRILLER', 7.6),
    ('The Sixth Sense', 'THRILLER', 8.1),
    ('The Cabin in the Woods', 'HORROR', 7.0),
    ('The Hunger Games', 'ACTION', 7.7),
    ('Spider-Man: No Way Home', 'ACTION', 8.4);
